"""in2

Revision ID: 561693009f02
Revises: e466c9c9c21e
Create Date: 2023-11-09 18:59:22.740058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561693009f02'
down_revision = 'e466c9c9c21e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_map', sa.Column('timestamppp', sa.DateTime(), nullable=True))
    op.drop_index('ix_url_map_timestamp', table_name='url_map')
    op.create_index(op.f('ix_url_map_timestamppp'), 'url_map', ['timestamppp'], unique=False)
    op.drop_column('url_map', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_map', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_url_map_timestamppp'), table_name='url_map')
    op.create_index('ix_url_map_timestamp', 'url_map', ['timestamp'], unique=False)
    op.drop_column('url_map', 'timestamppp')
    # ### end Alembic commands ###
