"""empty message

Revision ID: 982626d660c7
Revises: 2986c8d845cc
Create Date: 2023-11-15 22:05:10.937653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982626d660c7'
down_revision = '2986c8d845cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'url_map', ['short'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'url_map', type_='unique')
    # ### end Alembic commands ###
